#!/usr/bin/env bash
# =============================================================================
# inject-back-to-docs.sh — Adds the "← Back to docs" anchor to a generated page
# Usage: .github/scripts/docs/inject-back-to-docs.sh <index.html> [<index.html>...]
#
# Produces: each named file, edited in place, carrying exactly one anchor with
# id="back-to-docs" immediately after its <body> tag.
#
# CI invokes it from two places, which is the whole reason it is a script and
# not a line inside either of them:
#   docs.yml (reports job)   — on the coverage and Compodoc trees, after the
#                              artifact download and BEFORE the publish steps
#   build-openapi-docs.sh    — on the Redocly page it has just rendered
# and docs-pr-check.yml runs it twice against a throwaway fixture, because a
# pull request has no report artifact to exercise it on.
#
# Failure mode: LOUD, always. A missing file, a page with no <body> tag, or any
# outcome other than exactly one anchor exits non-zero naming the file. That is
# the point of the script — see the note on the assertion below.
#
# Prerequisites: none beyond coreutils and sed.
#
# WHY the four published surfaces need this at all: each is generated by a tool
# that owns its whole page (JaCoCo, istanbul, Compodoc, Redocly), so none of
# them can carry the site chrome, and a reader who lands on one has no way back
# to the documentation site without editing the URL.
# =============================================================================
set -euo pipefail

ANCHOR_ID="back-to-docs"

# One definition for all four surfaces. A change to the wording, the colour or
# the position is a change to this line and to nothing else — before this script
# existed the markup lived inside build-openapi-docs.sh, where a second surface
# could only be served by copying it.
ANCHOR='<a id="back-to-docs" href="/maintenance-assistant/" style="position:fixed;top:8px;right:12px;z-index:9999;font:14px sans-serif;padding:6px 12px;background:#0d9488;color:#fff;text-decoration:none;border-radius:4px;box-shadow:0 1px 4px rgba(0,0,0,0.2);">\&larr; Back to docs</a>'

if [ "$#" -eq 0 ]; then
  echo "Usage: inject-back-to-docs.sh <index.html> [<index.html>...]" >&2
  exit 1
fi

inject_one() {
  local FILE="$1"

  # A caller naming a file that is not there has the wrong path, not an empty
  # tree: every invocation site knows whether its artifact exists.
  if [ ! -f "$FILE" ]; then
    echo "✗ back-to-docs: no such file — $FILE" >&2
    return 1
  fi

  local COUNT
  COUNT="$(grep -c "id=\"$ANCHOR_ID\"" "$FILE" || true)"

  # Idempotent by design: docs.yml publishes with keep_files, so a tree can be
  # re-injected on a later run, and a second anchor would stack on the first.
  if [ "$COUNT" -eq 0 ]; then
    # The leading & is sed's "whatever matched", i.e. the <body> tag itself, so
    # the anchor lands immediately AFTER it and the tag survives. The ampersand
    # inside $ANCHOR is escaped for the same reason, in the other direction.
    sed -i "s|<body[^>]*>|&$ANCHOR|" "$FILE"
    COUNT="$(grep -c "id=\"$ANCHOR_ID\"" "$FILE" || true)"
  else
    echo "ℹ️  back-to-docs: already present in $FILE — left alone"
    return 0
  fi

  # THE ASSERTION, and it is the reason this script exists as more than a sed.
  # `sed` whose pattern matches nothing exits 0 and changes the file not at all,
  # so the caller's success message prints over a page that has no anchor —
  # exactly the "check passes for the wrong reason" class this repository has
  # been burned by twice. A generator that stops emitting a plain <body> tag
  # must break the build, not the published page.
  if [ "$COUNT" -ne 1 ]; then
    echo "✗ back-to-docs: expected exactly 1 anchor in $FILE, found $COUNT" >&2
    echo "  The page has no <body> tag the injector recognises, or it was" >&2
    echo "  injected twice. Nothing is published from an unverified page." >&2
    return 1
  fi

  # Counting the anchor alone is itself a check that can pass for the wrong
  # reason: a replacement that CONSUMED the <body> tag instead of keeping it
  # still leaves exactly one anchor behind, on a page the browser now renders
  # without a body element. Found that way while writing this script, which is
  # the argument for the second assertion rather than against the first.
  if ! grep -q "<body" "$FILE"; then
    echo "✗ back-to-docs: the <body> tag did not survive injection in $FILE" >&2
    return 1
  fi

  echo "✓ back-to-docs injected into $FILE"
}

for target in "$@"; do
  inject_one "$target"
done
